title: pageXML
url: "https://ir-g.uk/pagexml"

# MENU

menu:
  -
    title: Home 
    url: /
  - 
    title: Blog
    url: /blog
  -
    title: Releases
    url: /releases

# Github data

github:
  repo: isaacrg/pagexml
  branch: gh-pages

# Build settings
markdown:     kramdown
highlighter: rouge
kramdown:
  input: GFM
# permalink:    pretty
sass:
  compressed: true
permalink: "/blog/:year-:month-:day-:title"
# As according to https://help.github.com/articles/sitemaps-for-github-pages/
gems:
  - jekyll-sitemap

# Set Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
      
