title: pageXML
url: "http://isaacrg.me/pagexml"


# Build settings
markdown:     kramdown
highlighter: pygments
kramdown:
  input: GFM
# permalink:    pretty
paginate: 5
paginate_path: "blog/page-:num/"
sass:
  compressed: true

# As according to https://help.github.com/articles/sitemaps-for-github-pages/
gems:
  - jekyll-sitemap

# Set Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
      
